ALTER TABLE "channel" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profile" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "team" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "channel_select" ON "channel" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((kind = 'global' OR team_id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
CREATE POLICY "profile_select" ON "profile" AS PERMISSIVE FOR SELECT TO "authenticated" USING (auth.uid() IS NOT NULL);--> statement-breakpoint
CREATE POLICY "team_select" ON "team" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
ALTER POLICY "issue_select" ON "issue" TO "authenticated" USING ((team_id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
ALTER POLICY "issue_insert" ON "issue" TO "authenticated" WITH CHECK ((team_id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
ALTER POLICY "issue_update" ON "issue" TO "authenticated" USING ((team_id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin')) WITH CHECK ((team_id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
ALTER POLICY "issue_delete" ON "issue" TO "authenticated" USING ((team_id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
ALTER POLICY "message_select" ON "message" TO "authenticated" USING ((channel_id IN (SELECT id FROM channel WHERE kind = 'global' OR team_id IN (SELECT board_member_team_ids()))) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
ALTER POLICY "message_insert" ON "message" TO "authenticated" WITH CHECK ((channel_id IN (SELECT id FROM channel WHERE kind = 'global' OR team_id IN (SELECT board_member_team_ids()))) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));--> statement-breakpoint
ALTER POLICY "team_member_select" ON "team_member" TO "authenticated" USING ((team_id IN (SELECT board_member_team_ids())) OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb -> 'app_metadata' -> 'roles', '[]'::jsonb)) AS r(role) WHERE r.role = 'admin'));